/**
 * Gera as tabelas de docs/DESIGN_SYSTEM.md a partir dos tokens, para código e documento não divergirem.
 * O teste `documentacao.test.ts` compara; `npm run design:docs` reescreve os blocos entre os marcadores
 * `<!-- tokens:ID:inicio -->` e `<!-- tokens:ID:fim -->`. Todo token novo precisa de uma descrição em DESCRICOES.
 */
import { PARES_DE_CONTRASTE, razaoDoPar } from './a11y';
import type { IconKey } from '../data/reminders';
import { GIRO_NA_LISTA, ICON_NAME, TAB_ICON, UI_ICON } from './icons';
import { borderWidth, colors, fontFamily, fontSize, gradients, iconStroke, layout, lineHeight, motion, opacity, palette, radius, shadow, size, space, textStyles } from './tokens';

type Folha = { caminho: string; valor: string | number };

const achatar = (objeto: object, prefixo: string): Folha[] =>
  Object.entries(objeto).flatMap(([chave, valor]) =>
    valor !== null && typeof valor === 'object' ? achatar(valor, `${prefixo}.${chave}`) : [{ caminho: `${prefixo}.${chave}`, valor: valor as string | number }],
  );

const GRUPOS = { palette, colors, fontSize, lineHeight, fontFamily, space, radius, borderWidth, size, iconStroke, opacity, shadow, gradients, motion, layout };

/** Todo token existente, como "colors.text.primary". Os estilos de texto contam como um token cada (`textStyles.body`). */
export const CAMINHOS_DE_TOKEN: string[] = [
  ...Object.entries(GRUPOS).flatMap(([nome, grupo]) => achatar(grupo, nome).map((f) => f.caminho)),
  ...Object.keys(textStyles).map((nome) => `textStyles.${nome}`),
];

/** Uso de cada token. `*` vale por um trecho do caminho ("colors.category.*.bg"). */
const DESCRICOES: Record<string, string> = {
  'palette.forest900': 'Chip de filtro selecionado',
  'palette.forest800': 'Botão escuro (secundário)',
  'palette.forestHover': 'Botão escuro com o ponteiro em cima (web)',
  'palette.forestPressed': 'Botão escuro pressionado',
  'palette.forest700': 'Foco, spinner e faixa dos avisos informativos',
  'palette.forest600': 'Preenchimento do controle deslizante do raio',
  'palette.mint50': 'Fundo do aviso de sucesso',
  'palette.mint100': 'Círculo atrás do ícone do estado vazio',
  'palette.mintTint': 'Fundo do aviso informativo',
  'palette.mintBrand': 'Fundo do ícone do app, da tela de abertura e do favicon',
  'palette.mintBrandEnd': 'Fim do degradê do ícone do app',
  'palette.brandInk': 'Símbolo do ícone do app',
  'palette.orange500': 'Cor de ação (botão primário). Nunca como cor de texto sobre fundo claro',
  'palette.orangeHover': 'Botão primário com o ponteiro em cima (web)',
  'palette.orangePressed': 'Botão primário pressionado',
  'palette.orangeAA': 'Alternativa ao laranja que cumpre 4,5:1 com texto branco',
  'palette.white': 'Campos, painéis, folhas e texto sobre fundo escuro',
  'palette.cream100': 'Superfície de cartões e da barra de abas',
  'palette.cream200': 'Fundo de página',
  'palette.sand': 'Palco atrás da coluna do app (web) e trilho do controle segmentado',
  'palette.chipOff': 'Chip de filtro não selecionado',
  'palette.chipRing': 'Contorno do chip não selecionado',
  'palette.borderSubtle': 'Borda de campos de formulário',
  'palette.borderStrong': 'Contorno do botão sem fundo',
  'palette.divider': 'Divisórias',
  'palette.trackOff': 'Trilho do interruptor desligado',
  'palette.ink900': 'Texto principal',
  'palette.inkBrand': 'Rótulo da aba ativa',
  'palette.ink700': 'Texto secundário',
  'palette.ink650': 'Texto de exemplo (placeholder)',
  'palette.ink600': 'Só ícones e elementos sem texto: não serve como cor de texto',
  'palette.textAccent': 'Valor em destaque dentro do texto',
  'palette.red700': 'Texto e borda de erro',
  'palette.red200': 'Borda da zona de perigo',
  'palette.red100': 'Fundo do aviso de erro',
  'palette.red50': 'Fundo da zona de perigo',
  'palette.green700': 'Texto de sucesso',
  'palette.mapBlue': 'Posição atual da pessoa no mapa',
  'palette.mapGray': 'Marcador de lembrete pausado no mapa',
  'palette.forest950': 'Palco escuro atrás da coluna do app na web, como no app original',
  'palette.forestPin': 'Pino do mapa no formulário de novo lembrete',
  'palette.headerTop': 'Degradê verde dos cabeçalhos e das telas de conta: topo',
  'palette.headerMid': 'Degradê verde dos cabeçalhos e das telas de conta: meio',
  'palette.headerBottom': 'Degradê verde dos cabeçalhos e das telas de conta: base',
  'palette.mist300': 'Degradê claro do cabeçalho do formulário: topo',
  'palette.mist100': 'Degradê claro do cabeçalho do formulário: meio',
  'palette.mint200': 'Contorno da faixa de seleção do horário',
  'palette.mint400': 'Anel de foco sobre fundo escuro',
  'palette.toggleCardOn': 'Interruptor ligado no cartão de lembrete (o verde da imagem, #30AB7B, escurecido 5% para 3:1 com o cartão)',
  'palette.toggleThumb': 'Bolinha do interruptor',
  'palette.toggleFormOn': 'Interruptor ligado nos formulários e nas configurações',
  'palette.frost': 'Botão translúcido (ações do sucesso e Cancelar)',
  'palette.frostHover': 'Botão translúcido com o ponteiro em cima (web)',
  'palette.frostPressed': 'Botão translúcido pressionado',
  'palette.frostInk': 'Texto dos botões translúcidos',
  'palette.danger': 'Botão de perigo (Excluir lembrete)',
  'palette.dangerHover': 'Botão de perigo com o ponteiro em cima (web)',
  'palette.dangerPressed': 'Botão de perigo pressionado',
  'palette.sheet': 'Folha de cantos altos da lista e das configurações',
  'palette.alertErrorBg': 'Fundo do aviso de erro nas configurações',
  'palette.alertErrorInk': 'Texto do aviso de erro nas configurações',
  'palette.alertInfoInk': 'Texto do aviso informativo',
  'palette.statusGreen': 'Ponto do selo "Ativo"',
  'palette.onDark100': 'Texto sobre verde escuro: título',
  'palette.onDark200': 'Texto sobre verde escuro: subtítulo',
  'palette.onDark300': 'Texto sobre verde escuro: apoio',
  'palette.onDark400': 'Texto sobre verde escuro: o mais suave',
  'palette.headerSubtitle': 'Subtítulo dos cabeçalhos verdes ("5 lembretes ativos")',
  'palette.chipCount': 'Contagem dentro do chip de filtro não selecionado',
  'palette.tipCircle': 'Círculo atrás da lâmpada do cartão de dica',
  'palette.tipInk': 'Lâmpada do cartão de dica',
  'palette.tipText': 'Texto do cartão de dica',
  'palette.iconRadius': 'Ícone do raio no cartão de lembrete por local',
  'palette.mint300': 'Destaque do título do Onboarding ("de tudo!")',
  'palette.mintIcon': 'Ícones dos balões do Onboarding',
  'palette.onboardingBg': 'Fundo do Onboarding enquanto a foto carrega',
  'palette.pagerOn': 'Ponto da página ativa do Onboarding',
  'palette.mapControl': 'Botões que flutuam sobre o mapa do formulário',
  'palette.mapControlPressed': 'Botão sobre o mapa pressionado',
  'palette.mapControlDivider': 'Divisória entre os botões de zoom do mapa',
  'palette.suggestionHover': 'Sugestão de endereço com o ponteiro em cima (web)',
  'palette.optionBadge': 'Selo de seleção dos cartões de modo e das linhas escolhidas',
  'palette.sliderThumb': 'Bolinha do controle deslizante do raio',
  'palette.hint': 'Subtítulo do cabeçalho claro do formulário',
  'palette.wheelItem': 'Número não escolhido da roda do horário (o app usa `colors.text.secondary` para dar contraste)',
  'palette.rowHover': 'Linha de menu com o ponteiro em cima (web)',
  'palette.rowPressed': 'Linha de menu pressionada',
  'palette.dangerTint': 'Círculo do ícone de excluir e linha de excluir pressionada',
  'palette.dangerRowHover': 'Linha de excluir com o ponteiro em cima (web)',
  'palette.iconDots': 'Reticências "mais opções" do cartão de lembrete',
  'palette.tabInactive': 'Rótulo e ícone da aba inativa (medido nas capturas)',
  'palette.homeIndicator': 'Traço "home" do iOS sob a barra de abas',

  'colors.bg.page': 'Fundo de todas as telas',
  'colors.bg.stage': 'Palco atrás da coluna do app na web (tablet e computador)',
  'colors.bg.card': 'Superfície de cartões e da barra de abas',
  'colors.bg.field': 'Campos de formulário, painéis e folhas',
  'colors.bg.disabled': 'Campo desabilitado',
  'colors.text.primary': 'Texto principal e títulos',
  'colors.text.secondary': 'Subtítulos, dicas e metadados',
  'colors.text.placeholder': 'Texto de exemplo dentro de campos vazios',
  'colors.text.accent': 'Valor em destaque dentro do texto (raio, contagens, e-mail da conta)',
  'colors.text.brand': 'Rótulo da aba ativa',
  'colors.text.onAction': 'Rótulo sobre o botão primário',
  'colors.text.onDark': 'Rótulo sobre fundo escuro (botão escuro, chip selecionado)',
  'colors.text.danger': 'Mensagens e rótulos de erro',
  'colors.text.success': 'Mensagens e rótulos de sucesso',
  'colors.icon.default': 'Ícones sobre fundo claro',
  'colors.icon.muted': 'Ícones secundários e da aba inativa (nunca para texto)',
  'colors.icon.radius': 'Ícone do raio no cartão de lembrete por local',
  'colors.map.control': 'Botões que flutuam sobre o mapa do formulário',
  'colors.map.controlPressed': 'Botão sobre o mapa pressionado',
  'colors.map.controlDivider': 'Divisória entre os botões de zoom do mapa',
  'colors.control.suggestionHover': 'Sugestão de endereço com o ponteiro em cima (web)',
  'colors.control.badge': 'Selo de escolhido (o visto) dos cartões de modo e das linhas escolhidas',
  'colors.control.sliderThumb': 'Bolinha do controle deslizante do raio',
  'colors.control.haloHover': 'Halo atrás das reticências do cartão com o ponteiro em cima (web)',
  'colors.control.haloPressed': 'Halo atrás das reticências do cartão pressionado',
  'colors.bg.iconCircle': 'Círculo atrás do ícone das linhas de menu (Editar, Alterar senha)',
  'colors.control.rowHover': 'Linha de menu com o ponteiro em cima (web)',
  'colors.control.rowPressed': 'Linha de menu pressionada',
  'colors.control.dangerRowHover': 'Linha de excluir com o ponteiro em cima (web)',
  'colors.control.dangerRowPressed': 'Linha de excluir pressionada',
  'colors.feedback.dangerCircle': 'Círculo atrás do ícone de excluir e de sair',
  'colors.text.onDarkAccent': 'Destaque do título do Onboarding ("de tudo!")',
  'colors.text.brandAccent': 'Letras "Ai" do nome da marca no Onboarding',
  'colors.icon.onDarkMint': 'Ícones dos balões do Onboarding',
  'colors.onboarding.bg': 'Fundo do Onboarding enquanto a foto carrega',
  'colors.onboarding.pagerOn': 'Ponto da página ativa do Onboarding',
  'colors.onboarding.pagerOff': 'Pontos das outras páginas do Onboarding',
  'colors.glass.balloon': 'Balão de vidro do Onboarding ("Na hora certa", "No lugar certo")',
  'colors.glass.balloonRing': 'Contorno do balão de vidro do Onboarding',
  'colors.glass.featureFill': 'Fundo do círculo dos benefícios do Onboarding',
  'colors.glass.featureRing': 'Contorno do círculo dos benefícios do Onboarding',
  'colors.glass.divider': 'Divisória vertical entre os benefícios do Onboarding',
  'colors.icon.dots': 'Reticências "mais opções" do cartão de lembrete',
  'colors.icon.tip': 'Lâmpada do cartão de dica',
  'colors.text.onHeader': 'Subtítulo sobre o cabeçalho verde',
  'colors.text.chip': 'Rótulo do chip de filtro não selecionado',
  'colors.text.tip': 'Texto do cartão de dica',
  'colors.text.chipCount': 'Contagem dentro do chip de filtro não selecionado',
  'colors.feedback.tipCircle': 'Círculo atrás da lâmpada do cartão de dica',
  'colors.border.selectedBand': 'Contorno da faixa que marca o número escolhido nas rodas do horário',
  'colors.border.focusOnDark': 'Anel de foco e borda do campo em foco sobre o verde escuro',
  'colors.glass.field': 'Campo de busca sobre o cabeçalho verde',
  'colors.glass.fieldFocus': 'Campo de busca em foco',
  'colors.action.primary': 'Fundo do botão primário',
  'colors.action.primaryHover': 'Botão primário com o ponteiro em cima (web)',
  'colors.action.primaryPressed': 'Botão primário pressionado',
  'colors.action.primaryAA': 'Alternativa do botão primário que cumpre 4,5:1 com texto branco',
  'colors.action.secondary': 'Fundo do botão escuro (secundário)',
  'colors.action.secondaryHover': 'Botão escuro com o ponteiro em cima (web)',
  'colors.action.secondaryPressed': 'Botão escuro pressionado',
  'colors.border.field': 'Borda de campos de formulário',
  'colors.border.strong': 'Contorno do botão sem fundo (ghost)',
  'colors.border.divider': 'Divisórias',
  'colors.border.chip': 'Contorno do chip não selecionado',
  'colors.border.focus': 'Borda do campo em foco e anel de foco',
  'colors.border.danger': 'Borda do campo com erro e do botão de exclusão',
  'colors.border.dangerSoft': 'Borda da zona de perigo',
  'colors.control.on': 'Preenchimento do controle deslizante do raio',
  'colors.control.off': 'Interruptor desligado',
  'colors.control.thumb': 'Bolinha do interruptor',
  'colors.control.chipOn': 'Chip de filtro selecionado',
  'colors.control.chipOff': 'Chip de filtro não selecionado',
  'colors.control.segmentTrack': 'Trilho do controle segmentado',
  'colors.control.segmentThumb': 'Opção selecionada do controle segmentado',
  'colors.feedback.dangerBg': 'Fundo do aviso de erro',
  'colors.feedback.dangerWash': 'Fundo da zona de perigo',
  'colors.feedback.successBg': 'Fundo do aviso de sucesso',
  'colors.feedback.infoBg': 'Fundo do aviso informativo (ex.: "você está dentro do raio")',
  'colors.feedback.infoBar': 'Faixa lateral do aviso informativo',
  'colors.feedback.emptyCircle': 'Círculo atrás do ícone do estado vazio',
  'colors.brand.tile': 'Fundo do ícone do app, da tela de abertura e do favicon',
  'colors.brand.tileEnd': 'Fim do degradê do ícone do app',
  'colors.brand.glyph': 'Símbolo do ícone do app',
  'colors.spinner': 'Indicador de carregamento sobre fundo claro',
  'colors.overlay': 'Véu atrás de modais e folhas',
  'colors.map.me': 'Posição atual da pessoa no mapa',
  'colors.map.ring': 'Aro branco em volta dos marcadores do mapa',
  'colors.map.paused': 'Marcador de lembrete pausado no mapa',
  'colors.map.background': 'Fundo do mapa enquanto os mapas carregam',
  'colors.category.*.bg': 'Fundo do círculo do ícone da categoria',
  'colors.category.*.bar': 'Faixa lateral do cartão da categoria',
  'colors.category.*.ink': 'Glifo do ícone da categoria',
  'colors.category.*.pin': 'Marcador da categoria no mapa',
  'colors.category.*.tag': 'Fundo da etiqueta do cartão ("Por horário", "Por local")',
  'colors.category.*.fg': 'Ícone da etiqueta do cartão',
  'colors.category.*.tagInk': 'Texto da etiqueta: o ícone da etiqueta escurecido até dar 4,5:1 com o fundo dela',
  'colors.bg.sheet': 'Folha de cantos altos da lista e das configurações',
  'colors.text.onDarkWarm': 'Título sobre verde escuro',
  'colors.text.onDarkSoft': 'Subtítulo sobre verde escuro',
  'colors.text.onDarkMuted': 'Texto de apoio sobre verde escuro',
  'colors.text.onDarkFaint': 'Texto mais suave sobre verde escuro',
  'colors.text.onFrost': 'Rótulo dos botões translúcidos',
  'colors.action.danger': 'Fundo do botão de perigo',
  'colors.action.dangerHover': 'Botão de perigo com o ponteiro em cima (web)',
  'colors.action.dangerPressed': 'Botão de perigo pressionado',
  'colors.action.frost': 'Fundo dos botões translúcidos',
  'colors.action.frostHover': 'Botão translúcido com o ponteiro em cima (web)',
  'colors.action.frostPressed': 'Botão translúcido pressionado',
  'colors.control.onCard': 'Interruptor ligado no cartão de lembrete',
  'colors.control.onForm': 'Interruptor ligado nos formulários e nas configurações',
  'colors.feedback.errorBg': 'Fundo do aviso de erro nas configurações',
  'colors.feedback.errorInk': 'Texto do aviso de erro nas configurações',
  'colors.feedback.infoInk': 'Texto do aviso informativo',
  'colors.status.active': 'Ponto do selo "Ativo"',
  'colors.tab.inactive': 'Rótulo e ícone da aba inativa',
  'colors.tab.indicator': 'Traço "home" do iOS sob a barra de abas',
  'colors.glass.fill': 'Véu do botão de vidro sobre o verde escuro',
  'colors.glass.fillHover': 'Botão de vidro com o ponteiro em cima (web)',
  'colors.glass.fillPressed': 'Botão de vidro pressionado',
  'colors.glass.border': 'Borda do botão de vidro',
  'colors.map.pin': 'Pino do mapa no formulário de novo lembrete',
  'colors.map.haloFill': 'Preenchimento do círculo do raio de aviso',
  'colors.map.haloLine': 'Contorno do círculo do raio de aviso',
  'colors.map.pinShadow': 'Sombra do pino do mapa no formulário',
  'gradients.rodaDeHorario': 'Esmaecimento das rodas do horário (números longe do meio somem no fundo da folha)',
  'gradients.divisorVertical': 'Divisória vertical entre os benefícios do Onboarding',
  'gradients.marcaTile': 'Tile da marca no cabeçalho: o menta do ícone do app, a 160°',
  'gradients.cabecalhoVerde': 'Cabeçalho verde da lista e das configurações (345 du de altura)',
  'gradients.contas': 'Fundo das telas de conta',
  'gradients.cabecalhoClaro': 'Cabeçalho claro do formulário de novo lembrete',
  'gradients.esmaecerParaPagina': 'Esmaecimento atrás do botão fixo do formulário',

  'fontSize.micro': 'Tags e legendas: o piso de legibilidade do app',
  'fontSize.caption': 'Dicas, metadados e mensagens de campo',
  'fontSize.body': 'Texto corrente e rótulos',
  'fontSize.bodyLg': 'Texto de leitura, campos e botões',
  'fontSize.heading': 'Títulos de seção',
  'fontSize.title': 'Títulos de tela e de estados',
  'fontSize.display': 'Nome do app nas telas de conta',
  'lineHeight.*': 'Altura de linha do tamanho de mesmo nome',
  'fontFamily.regular': 'Nunito Sans 400: texto corrente',
  'fontFamily.medium': 'Nunito Sans 500: ênfase leve',
  'fontFamily.semibold': 'Nunito Sans 600: rótulos e valores',
  'fontFamily.bold': 'Nunito Sans 700: botões e destaques',
  'fontFamily.serif': 'Source Serif 4 700: títulos de tela, de seção e de cartão',
  'textStyles.display': 'Título grande: nome do app nas telas de conta e títulos das páginas públicas',
  'textStyles.title': 'Título de tela e de estado vazio',
  'textStyles.heading': 'Título de seção ("Hoje", "Amanhã") e de cabeçalho',
  'textStyles.sheetTitle': 'Título de folha inferior (Excluir lembrete?, Horário, Repetir): o tamanho de título com altura de linha 1,2',
  'textStyles.bodyLg': 'Texto de leitura (política de privacidade) e de campos',
  'textStyles.body': 'Texto corrente',
  'textStyles.label': 'Rótulo de campo e de linha',
  'textStyles.button': 'Rótulo de botão',
  'textStyles.caption': 'Dica, metadado e mensagem de campo',
  'textStyles.micro': 'Legenda mínima',

  'space.hair': 'Ajuste fino, como título e metadado do cartão',
  'space.xs': 'Espaço mínimo entre textos',
  'space.sm': 'Entre itens próximos: chips, ícone e texto',
  'space.md': 'Padding de cartões e campos; entre cartões',
  'space.lg': 'Margem lateral das telas e padding de painéis',
  'space.xl': 'Entre grupos de conteúdo; padding das telas de conta',
  'space.xxl': 'Entre seções',
  'space.huge': 'Respiro no fim de listas rolantes',
  'space.giant': 'Respiro do estado vazio',
  'radius.xs': 'Selos pequenos',
  'radius.sm': 'Avisos e miniaturas',
  'radius.md': 'Campos, cartões e controles retangulares',
  'radius.lg': 'Painéis grandes',
  'radius.sheet': 'Topo de folhas e modais',
  'radius.pill': 'Botões, chips e círculos',
  'borderWidth.hairline': 'Borda de campo, de botão sem fundo e de chip',
  'borderWidth.focus': 'Anel de foco e cartão em destaque',
  'borderWidth.bar': 'Faixa lateral de avisos e de cartões',
  'size.touch': 'Área mínima de toque (44, o padrão do iOS)',
  'size.button': 'Altura dos botões',
  'radius.form': 'Cartões do formulário de novo lembrete',
  'radius.field': 'Campos e seletores dentro dos cartões do formulário',
  'shadow.formCard': 'Cartão do formulário (anel branco por dentro e sombra suave)',
  'shadow.field': 'Campo branco do formulário (anel cinza por dentro)',
  'shadow.fieldHover': 'Campo do formulário com o ponteiro em cima (web)',
  'shadow.fieldFocus': 'Campo do formulário em foco (anel verde e halo)',
  'shadow.optionOn': 'Cartão de modo escolhido (anel verde por dentro)',
  'shadow.slider': 'Bolinha do controle deslizante',
  'size.suggestions.maxHeight': 'Sugestões de endereço: altura máxima da lista (o resto rola)',
  'size.suggestions.padding': 'Sugestões de endereço: recuo da lista',
  'size.suggestions.gap': 'Sugestões de endereço: vão entre o campo e a lista',
  'shadow.suggestions': 'Lista de sugestões de endereço (sombra funda e anel cinza)',
  'size.mapControl.button': 'Mapa do formulário: lado dos botões de centralizar e zoom',
  'size.mapControl.pill': 'Mapa do formulário: altura da pílula "Usar minha localização"',
  'size.mapControl.icon': 'Mapa do formulário: ícone dentro dos botões',
  'size.form.header': 'Formulário: altura da arte do cabeçalho claro',
  'size.form.nav': 'Formulário: botões redondos de voltar e de conta',
  'size.form.navTop': 'Formulário: distância dos botões até o topo (desce com a barra de status do aparelho)',
  'size.form.navSide': 'Formulário: distância dos botões até as bordas',
  'size.form.map': 'Formulário: altura do mapa',
  'size.form.mapRadius': 'Formulário: raio do mapa',
  'size.form.cta': 'Formulário: altura do botão "Criar lembrete"',
  'size.form.ctaCircle': 'Formulário: círculo da seta do botão "Criar lembrete"',
  'size.form.dock': 'Formulário: altura da base que esmaece atrás do botão fixo',
  'colors.glass.ctaCircle': 'Círculo da seta dentro do botão "Criar lembrete"',
  'size.form.cardPadding': 'Formulário: recuo interno dos cartões',
  'size.form.circle': 'Formulário: círculo do ícone do cartão Descrição',
  'size.form.field': 'Formulário: altura do campo e dos seletores',
  'size.form.fieldIcon': 'Formulário: ícone dentro do seletor de data e hora',
  'size.form.option': 'Formulário: altura do cartão de modo',
  'size.form.optionCircle': 'Formulário: círculo do ícone do cartão de modo',
  'size.form.optionIcon': 'Formulário: ícone dentro do cartão de modo',
  'size.form.optionBadge': 'Formulário: selo de escolhido do cartão de modo',
  'size.form.optionCheck': 'Formulário: visto dentro do selo de escolhido',
  'size.form.optionRadio': 'Formulário: anel do cartão de modo não escolhido',
  'size.form.sliderTrack': 'Formulário: espessura do trilho do controle deslizante',
  'size.form.sliderThumb': 'Formulário: bolinha do controle deslizante',
  'size.form.sliderHeight': 'Formulário: altura da área de toque do controle deslizante',
  'size.tabBar.top': 'Barra de abas: espaço acima das abas',
  'size.tabBar.item': 'Barra de abas: altura de cada aba (ícone, vão e rótulo)',
  'size.tabBar.bottom': 'Barra de abas: espaço mínimo embaixo (a área segura do sistema o substitui quando é maior)',
  'size.tabBar.gap': 'Barra de abas: vão entre o ícone e o rótulo',
  'size.tabBar.icon': 'Barra de abas: lado do ícone',
  'palette.tabActiveIcon': 'Ícone da aba ativa',
  'colors.tab.activeIcon': 'Ícone da aba ativa',
  'opacity.tab': 'Aba da barra de abas pressionada',
  'size.iconCircle': 'Círculo do ícone de categoria',
  'size.emptyCircle': 'Círculo do ícone do estado vazio',
  'size.glassButton': 'Botão redondo de vidro do cabeçalho verde (busca e conta); o toque chega a 44 com `size.hitSlop`',
  'size.buttonCompact': 'Altura do botão compacto ("Novo lembrete" no cabeçalho)',
  'fontSize.wheel': 'Número da roda do horário',
  'fontSize.wheelOn': 'Número escolhido da roda do horário',
  'fontSize.colon': 'Dois-pontos entre as rodas do horário',
  'layout.wheelRows': 'Números visíveis de cada roda do horário',
  'size.form.row': 'Folha Repetir: altura mínima de cada linha',
  'size.form.rowLeft': 'Folha Repetir: recuo da esquerda',
  'size.form.rowRight': 'Folha Repetir: recuo da direita',
  'size.form.rowGap': 'Folha Repetir: vão entre o texto e a marca',
  'size.form.rowBadge': 'Folha Repetir: selo da linha escolhida',
  'size.form.rowRadio': 'Folha Repetir: anel das linhas não escolhidas',
  'size.form.rowCheck': 'Folha Repetir: visto do selo',
  'size.wheel.width': 'Roda do horário: largura de cada coluna',
  'size.wheel.item': 'Roda do horário: altura de cada número',
  'size.wheel.gap': 'Roda do horário: vão entre as colunas',
  'size.wheel.top': 'Roda do horário: espaço acima das rodas',
  'size.wheel.band.width': 'Roda do horário: largura da faixa da escolha',
  'size.wheel.band.radius': 'Roda do horário: raio da faixa da escolha',
  'size.calendar.day': 'Calendário: lado da célula de cada dia (toque de 44)',
  'size.calendar.selected': 'Calendário: círculo do dia escolhido',
  'size.calendar.arrow': 'Calendário: botão de trocar de mês',
  'fontSize.hero': 'Título grande do Onboarding (fora de `textStyles`: as duas linhas curtas pedem altura de linha 1)',
  'size.onboarding.side': 'Onboarding: margem dos lados',
  'size.onboarding.skipWidth': 'Onboarding: largura do botão "Pular"',
  'size.onboarding.skipHeight': 'Onboarding: altura do botão "Pular"',
  'size.onboarding.balloonLeft.width': 'Onboarding: balão "Na hora certa", largura',
  'size.onboarding.balloonLeft.height': 'Onboarding: balão "Na hora certa", altura',
  'size.onboarding.balloonRight.width': 'Onboarding: balão "No lugar certo", largura',
  'size.onboarding.balloonRight.height': 'Onboarding: balão "No lugar certo", altura',
  'size.onboarding.feature': 'Onboarding: círculo do ícone de cada benefício',
  'size.onboarding.featureIcon': 'Onboarding: ícone dentro do círculo do benefício',
  'size.onboarding.heroButton': 'Onboarding: altura do botão "Criar meu primeiro lembrete"',
  'size.onboarding.pagerWidth': 'Onboarding: largura de cada ponto da página',
  'size.onboarding.pagerHeight': 'Onboarding: altura de cada ponto da página',
  'size.onboarding.pagerGap': 'Onboarding: vão entre os pontos da página',
  'size.onboarding.brandName': 'Onboarding: tamanho do nome da marca',
  'layout.onboardingSceneRatio': 'Onboarding: altura da cena (pino e balões) como fração da largura, a proporção da arte (505 por 851)',
  'size.list.chipsTop': 'Lista: distância da borda da folha até os chips',
  'size.list.chipsGap': 'Lista: vão entre os chips',
  'size.list.listTop': 'Lista: espaço entre os chips e o primeiro título de seção',
  'size.list.sectionHead': 'Lista: altura do título de seção (Hoje, Amanhã, Esta semana)',
  'size.list.headGap': 'Lista: vão entre o título da seção e o primeiro cartão',
  'size.list.firstHeadGap': 'Lista: o mesmo vão na primeira seção',
  'size.list.cardGap': 'Lista: vão entre cartões',
  'size.list.sectionGap': 'Lista: vão entre seções',
  'size.list.tipGap': 'Lista: vão entre o último cartão e a dica',
  'size.list.emptyTop': 'Lista: espaço acima da mensagem de lista vazia',
  'size.menu.row': 'Linha do menu: altura mínima',
  'size.menu.circle': 'Linha do menu: círculo do ícone',
  'size.menu.icon': 'Linha do menu: ícone dentro do círculo',
  'size.menu.gap': 'Linha do menu: vão entre o círculo e o texto',
  'size.menu.paddingHorizontal': 'Linha do menu: recuo dos lados',
  'size.menu.listTop': 'Linha do menu: distância da lista até o título da folha',
  'size.tag.height': 'Etiqueta "Por horário" / "Por local": altura',
  'size.tag.left': 'Etiqueta: recuo antes do ícone',
  'size.tag.right': 'Etiqueta: recuo depois do texto',
  'size.tag.gap': 'Etiqueta: vão entre o ícone e o texto',
  'size.tag.icon': 'Etiqueta: lado do ícone',
  'size.tip.radius': 'Cartão de dica: raio',
  'size.tip.circle': 'Cartão de dica: círculo do ícone',
  'size.tip.padding': 'Cartão de dica: recuo do círculo até a borda',
  'size.tip.gap': 'Cartão de dica: vão entre o círculo e o texto',
  'size.card.minHeight': 'Cartão de lembrete: altura mínima (cresce com o texto e com a fonte grande)',
  'size.card.circle': 'Cartão de lembrete: círculo do ícone da categoria (alinhado ao topo)',
  'size.card.circleLeft': 'Cartão de lembrete: distância do círculo até a borda esquerda',
  'size.card.circleTop': 'Cartão de lembrete: distância do círculo até o topo',
  'size.card.glyph': 'Cartão de lembrete: glifo da categoria dentro do círculo',
  'size.card.textGap': 'Cartão de lembrete: vão entre o círculo e o texto',
  'size.card.metaIcon': 'Cartão de lembrete: ícone da data e do lugar',
  'size.card.metaGap': 'Cartão de lembrete: vão entre o ícone e o texto da data',
  'size.card.rightTop': 'Cartão de lembrete: distância da hora até o topo (lembrete por horário)',
  'size.card.localShift': 'Cartão de lembrete por local: quanto a coluna da hora desce (o cartão é mais alto)',
  'size.card.rightColumn': 'Cartão de lembrete: largura da coluna da hora e do interruptor',
  'size.card.rightInset': 'Cartão de lembrete: distância da coluna da direita até a borda',
  'size.card.dotsCenter': 'Botão "mais opções": distância do centro das reticências até a borda direita',
  'size.card.dotsWidth': 'Botão "mais opções": largura da área de toque',
  'size.card.dotsHeight': 'Botão "mais opções": altura da área de toque',
  'size.card.thumbWidth': 'Lembrete por local: largura da miniatura do mapa',
  'size.card.thumbHeight': 'Lembrete por local: altura da miniatura do mapa',
  'size.header.height': 'Altura da arte do cabeçalho verde',
  'size.header.contentTop': 'Topo da marca e dos botões no cabeçalho verde (sobe com a barra de status do aparelho)',
  'size.header.sheetTop': 'Onde começa a folha clara que sobe sobre o cabeçalho verde',
  'size.header.side': 'Margem lateral do conteúdo do cabeçalho verde',
  'size.header.brandGap': 'Vão entre o tile da marca e o nome',
  'size.header.brandTile': 'Lado do tile da marca',
  'size.header.brandGlyph': 'Lado do símbolo dentro do tile da marca',
  'size.header.searchHeight': 'Altura do campo de busca',
  'size.chip': 'Altura visível do chip (a área de toque chega a 44 com `size.hitSlop`)',
  'size.closeButton': 'Botão de fechar visível (a área de toque chega a 44 com `size.hitSlop`)',
  'size.hitSlop': 'Folga de toque ao redor de controles menores que 44',
  'size.mapPin.width': 'Largura do pino do mapa no formulário',
  'size.mapPin.height': 'Altura do pino do mapa no formulário (a ponta marca o local)',
  'size.icon.xs': 'Ícone dentro do botão compacto',
  'size.icon.sm': 'Ícones ao lado de texto pequeno',
  'size.icon.md': 'Ícones de ação',
  'size.icon.lg': 'Ícones de aba',
  'size.icon.xl': 'Ícone do estado vazio',
  'opacity.disabled': 'Controle desabilitado',
  'opacity.inactive': 'Cartão de lembrete pausado',
  'opacity.pressed': 'Toque em elementos que não trocam de cor',
  'shadow.card': 'Cartões e painéis (quase plano)',
  'shadow.float': 'Controles flutuantes',
  'shadow.cta': 'Brilho laranja do botão primário',
  'shadow.focus': 'Halo de 3 em volta do campo em foco, sobre a borda `colors.border.focus`',
  'motion.duration.fast': 'Feedback de toque (ms)',
  'motion.duration.base': 'Troca de estado (ms)',
  'motion.duration.slow': 'Entrada de modais (ms)',
  'motion.duration.scrim': 'Entrada do véu atrás de uma folha (ms)',
  'motion.duration.sheet': 'Subida de uma folha inferior (ms)',
  'motion.duration.toggle': 'Troca de estado do interruptor (ms)',
  'motion.ease.x1': 'Curva `ease` do CSS: cubic-bezier(x1, y1, x2, y2)',
  'motion.ease.y1': 'Curva `ease` do CSS: cubic-bezier(x1, y1, x2, y2)',
  'motion.ease.x2': 'Curva `ease` do CSS: cubic-bezier(x1, y1, x2, y2)',
  'motion.ease.y2': 'Curva `ease` do CSS: cubic-bezier(x1, y1, x2, y2)',
  'motion.curve.x1': 'Curva de entrada das folhas: cubic-bezier(x1, y1, x2, y2)',
  'motion.curve.y1': 'Curva de entrada das folhas: cubic-bezier(x1, y1, x2, y2)',
  'motion.curve.x2': 'Curva de entrada das folhas: cubic-bezier(x1, y1, x2, y2)',
  'motion.curve.y2': 'Curva de entrada das folhas: cubic-bezier(x1, y1, x2, y2)',
  'motion.pressedScale': 'Escala do botão pressionado',
  'iconStroke.tab': 'Ícone da aba inativa',
  'iconStroke.base': 'Ícone comum e da aba ativa',
  'iconStroke.glyph': 'Glifo da categoria do lembrete e lâmpada da dica',
  'iconStroke.ui': 'Ícone de interface (busca, conta, lupa, calendário do cartão)',
  'iconStroke.action': 'Ícone de ação (fechar, mais, seta, chevron)',
  'iconStroke.dots': 'Reticências "mais opções" do cartão',
  'iconStroke.check': 'Marca de seleção (visto) nas opções e nas linhas escolhidas',
  'layout.columnMax': 'Largura máxima da coluna do app na web (a das capturas de referência); no celular a coluna é a tela toda',
  'layout.readingMax': 'Largura máxima de texto corrido (política de privacidade)',
  'layout.sheetMaxHeight': 'Altura máxima de uma folha inferior, como fração da tela',
  'size.toggle.*.width': 'Interruptor (cartão · formulário): largura do trilho',
  'size.toggle.*.height': 'Interruptor (cartão · formulário): altura do trilho',
  'size.toggle.*.thumb': 'Interruptor (cartão · formulário): diâmetro da bolinha',
  'size.toggle.*.inset': 'Interruptor (cartão · formulário): folga da bolinha até a borda do trilho',
  'size.sheet.paddingTop': 'Folha inferior: espaço acima da alça',
  'size.sheet.paddingHorizontal': 'Folha inferior: margem dos lados',
  'size.sheet.paddingBottom': 'Folha inferior: espaço embaixo (a barra home do iOS)',
  'size.sheet.handleWidth': 'Alça da folha: largura (só enfeite, não arrasta)',
  'size.sheet.handleHeight': 'Alça da folha: altura',
  'size.sheet.handleGap': 'Vão entre a alça e o título da folha',
  'size.sheet.actionTop': 'Ação no canto da folha (o "Pronto" do horário): distância do topo',
  'size.sheet.actionRight': 'Ação no canto da folha: distância da direita',
  'shadow.sheet': 'Folha inferior (sombra para cima)',
  'shadow.tabBar': 'Barra de abas: filete e sombra para cima',
  'shadow.column': 'Coluna do app sobre o palco escuro, na web (tablet e computador)',
  'palette.tabBarBg': 'Fundo da barra de abas',
  'colors.tab.background': 'Fundo da barra de abas',
  // Tela de sucesso do lembrete (imagem 09; Design System, seção 11.12)
  'palette.sucessoCategoria': 'Círculo atrás do ícone da categoria no cartão de resumo do sucesso',
  'palette.sucessoDica': 'Círculo atrás da lâmpada da dica do sucesso',
  'palette.sucessoDado': 'Círculo dos dados do resumo (Data, Horário, Local, Repetir)',
  'palette.sucessoDadoAnel': 'Anel do círculo dos dados do resumo',
  'palette.sucessoSeloAnel': 'Anel do selo "Ativo"',
  'colors.icon.onFrost': 'Ícone dos botões de ação sobre o fundo `frost` (Editar, Excluir, Compartilhar)',
  'colors.sucesso.categoria': 'Círculo atrás do ícone da categoria no cartão de resumo',
  'colors.sucesso.dica': 'Círculo atrás da lâmpada da dica',
  'colors.sucesso.dado': 'Círculo dos dados do resumo (Data, Horário, Local, Repetir)',
  'colors.sucesso.dadoAnel': 'Anel do círculo dos dados do resumo',
  'colors.sucesso.seloAnel': 'Anel do selo "Ativo"',
  'fontSize.sucessoTitulo': 'Título da tela de sucesso, "Lembrete criado com sucesso!" (60,5 du no original; fora de `textStyles`: altura de linha 1,03, sem descendentes nas duas linhas fixas)',
  'fontSize.sucessoSubtitulo': 'Subtítulo da tela de sucesso (29 du no original)',
  'textStyles.sucessoSubtitulo': 'Subtítulo da tela de sucesso, em duas linhas',
  'shadow.cartaoDoSucesso': 'Cartões de resumo e de dica da tela de sucesso: só o anel branco por dentro',
  'size.sucesso.canvas': 'Sucesso: altura do canvas de rolagem (1848 du)',
  'size.sucesso.fechar': 'Sucesso: botão de vidro de fechar',
  'size.sucesso.fecharTop': 'Sucesso: distância do botão de fechar até o topo',
  'size.sucesso.fecharSide': 'Sucesso: distância do botão de fechar até a borda direita',
  'size.sucesso.fecharIcon': 'Sucesso: o X do botão de fechar',
  'size.sucesso.tituloTop': 'Sucesso: distância do título até o topo',
  'size.sucesso.tituloBox': 'Sucesso: altura reservada ao título (duas linhas)',
  'size.sucesso.subtituloGap': 'Sucesso: vão entre o título e o subtítulo',
  'size.sucesso.subtituloBox': 'Sucesso: altura reservada ao subtítulo (duas linhas)',
  'size.sucesso.resumoGap': 'Sucesso: vão entre o subtítulo e o cartão de resumo',
  'size.sucesso.side': 'Sucesso: recuo dos cartões até as bordas da tela',
  'size.sucesso.resumo.slot': 'Resumo: altura reservada ao cartão (a da variante com local), para as ações ficarem no mesmo lugar nas duas',
  'size.sucesso.resumo.pad*': 'Resumo: recuo interno do cartão',
  'size.sucesso.resumo.circle': 'Resumo: círculo do ícone da categoria',
  'size.sucesso.resumo.circleIcon': 'Resumo: ícone da categoria dentro do círculo',
  'size.sucesso.resumo.circleGap': 'Resumo: vão entre o círculo da categoria e o título',
  'size.sucesso.resumo.tituloMax': 'Resumo: largura máxima do título (quebra em duas linhas antes de chegar ao selo, como no original)',
  'size.sucesso.resumo.seloHeight': 'Resumo: altura do selo "Ativo"',
  'size.sucesso.resumo.seloLeft': 'Resumo: recuo do selo "Ativo" antes do ponto',
  'size.sucesso.resumo.seloRight': 'Resumo: recuo do selo "Ativo" depois do texto',
  'size.sucesso.resumo.seloGap': 'Resumo: vão entre o ponto e o texto do selo "Ativo"',
  'size.sucesso.resumo.seloDot': 'Resumo: ponto verde do selo "Ativo"',
  'size.sucesso.resumo.linhaGap': 'Resumo: vão entre o cabeçalho e a linha de Data e Horário',
  'size.sucesso.resumo.dado': 'Resumo: círculo do ícone de cada dado',
  'size.sucesso.resumo.dadoIcon': 'Resumo: ícone dentro do círculo do dado',
  'size.sucesso.resumo.dadoGap': 'Resumo: vão entre o círculo do dado e o texto',
  'size.sucesso.resumo.dadoColuna': 'Resumo: largura da coluna da Data (o Horário começa depois dela)',
  'size.sucesso.resumo.divisorAntes': 'Resumo: vão entre uma linha e o divisor que vem depois',
  'size.sucesso.resumo.divisorDepois': 'Resumo: vão entre o divisor e a linha seguinte',
  'size.sucesso.resumo.divisor': 'Resumo: espessura do divisor',
  'size.sucesso.resumo.thumbWidth': 'Resumo: largura da miniatura do mapa (lembrete por local)',
  'size.sucesso.resumo.thumbHeight': 'Resumo: altura da miniatura do mapa',
  'size.sucesso.resumo.thumbRadius': 'Resumo: raio da miniatura do mapa',
  'size.sucesso.acao.height': 'Ações (Editar, Excluir, Compartilhar): altura de cada botão',
  'size.sucesso.acao.radius': 'Ações: raio dos botões',
  'size.sucesso.acao.gap': 'Ações: vão entre os botões',
  'size.sucesso.acao.side': 'Ações: recuo da fileira até as bordas da tela',
  'size.sucesso.acao.icon': 'Ações: ícone de cada botão',
  'size.sucesso.acao.top': 'Ações: recuo do ícone até o topo do botão',
  'size.sucesso.acao.iconGap': 'Ações: vão entre o ícone e o rótulo',
  'size.sucesso.dica.height': 'Dica do sucesso: altura mínima do cartão',
  'size.sucesso.dica.circle': 'Dica do sucesso: círculo da lâmpada',
  'size.sucesso.dica.icon': 'Dica do sucesso: lâmpada dentro do círculo',
  'size.sucesso.dica.arrow': 'Dica do sucesso: seta à direita',
  'size.sucesso.dica.left': 'Dica do sucesso: recuo do círculo até a borda esquerda',
  'size.sucesso.dica.right': 'Dica do sucesso: recuo da seta até a borda direita',
  'size.sucesso.dica.gap': 'Dica do sucesso: vão entre o círculo e o texto',
  'size.sucesso.dica.textGap': 'Dica do sucesso: vão entre o título e o texto',
  'size.sucesso.cta': 'Sucesso: altura do botão escuro "Ver todos os lembretes"',
  'size.sucesso.ctaSide': 'Sucesso: recuo do botão escuro até as bordas',
  'size.sucesso.link': 'Sucesso: altura do link "Criar outro lembrete"',
  'size.sucesso.espaco.acoes': 'Sucesso: vão entre o cartão de resumo (reserva) e as ações',
  'size.sucesso.espaco.dica': 'Sucesso: vão entre as ações e a dica',
  'size.sucesso.espaco.cta': 'Sucesso: vão entre a dica e o botão escuro',
  'size.sucesso.espaco.link': 'Sucesso: vão entre o botão escuro e o link',
  'size.sucesso.espaco.fim': 'Sucesso: folga no fim da rolagem, abaixo do link',
};

const PADROES = Object.entries(DESCRICOES)
  .filter(([chave]) => chave.includes('*'))
  .map(([chave, texto]) => ({ regex: new RegExp(`^${chave.replace(/\./g, '\\.').replace(/\*/g, '[^.]+')}$`), texto }));

export function descricaoDoToken(caminho: string): string | undefined {
  return DESCRICOES[caminho] ?? PADROES.find((p) => p.regex.test(caminho))?.texto;
}

const cod = (v: string | number) => `\`${v}\``;
const tabela = (cabecalho: string[], linhas: (string | number)[][]) =>
  [`| ${cabecalho.join(' | ')} |`, `|${cabecalho.map(() => '---').join('|')}|`, ...linhas.map((l) => `| ${l.join(' | ')} |`)].join('\n');
const decimal = (n: number) => n.toFixed(2).replace('.', ',');
const nomeNaPaleta = new Map<string, string>(Object.entries(palette).map(([nome, hex]) => [hex, nome]));

const linhasSimples = (nome: keyof typeof GRUPOS, grupo: object) =>
  achatar(grupo, nome).map((f) => [cod(f.caminho), cod(f.valor), descricaoDoToken(f.caminho) ?? '']);

/** Cada bloco é o conteúdo entre os marcadores do documento. */
export function blocosGerados(): Record<string, string> {
  const { category, ...semCategorias } = colors;
  const categorias = Object.keys(category) as (keyof typeof category)[];
  const excecoes = [...new Set(PARES_DE_CONTRASTE.flatMap((p) => (p.excecao ? [p.excecao] : [])))];

  return {
    'cores-primitivas': tabela(['Token', 'Valor', 'Uso'], linhasSimples('palette', palette)),

    'cores-semanticas': tabela(
      ['Token', 'Valor', 'Vem da paleta', 'Uso'],
      achatar(semCategorias, 'colors').map((f) => {
        const daPaleta = nomeNaPaleta.get(String(f.valor));
        return [cod(f.caminho), cod(f.valor), daPaleta ? cod(`palette.${daPaleta}`) : '—', descricaoDoToken(f.caminho) ?? ''];
      }),
    ),

    'cores-categorias': tabela(
      ['Categoria', 'Fundo do ícone (`bg`)', 'Faixa (`bar`)', 'Glifo (`ink`)', 'Marcador no mapa (`pin`)', 'Etiqueta (`tag`)', 'Ícone da etiqueta (`fg`)', 'Texto da etiqueta (`tagInk`)'],
      categorias.map((c) => [cod(`colors.category.${c}`), cod(category[c].bg), cod(category[c].bar), cod(category[c].ink), cod(category[c].pin), cod(category[c].tag), cod(category[c].fg), cod(category[c].tagInk)]),
    ),

    contraste: [
      tabela(
        ['Frente', 'Fundo', 'Razão', 'Mínimo', 'Situação', 'Onde'],
        PARES_DE_CONTRASTE.map((p) => {
          const razao = razaoDoPar(p);
          return [cod(`colors.${p.fg}`), cod(`colors.${p.bg}`), `${decimal(razao)}:1`, `${String(p.min).replace('.', ',')}:1`, razao >= p.min ? (p.excecao ? '✓ exceção' : '✓') : '✗', p.uso];
        }),
      ),
      '',
      ...excecoes.map((e) => `- **Exceção:** ${e}`),
    ].join('\n'),

    'tipografia-estilos': tabela(
      ['Estilo', 'Tamanho', 'Altura de linha', 'Família', 'Uso'],
      Object.entries(textStyles).map(([nome, e]) => [cod(`textStyles.${nome}`), e.fontSize, e.lineHeight, cod(e.fontFamily), descricaoDoToken(`textStyles.${nome}`) ?? '']),
    ),

    'tipografia-escala': [
      tabela(['Token', 'Valor', 'Uso'], [...linhasSimples('fontSize', fontSize), ...linhasSimples('lineHeight', lineHeight), ...linhasSimples('fontFamily', fontFamily)]),
    ].join('\n'),

    espacamento: tabela(['Token', 'Valor', 'Uso'], linhasSimples('space', space)),
    raios: tabela(['Token', 'Valor', 'Uso'], linhasSimples('radius', radius)),
    bordas: tabela(['Token', 'Valor', 'Uso'], linhasSimples('borderWidth', borderWidth)),
    tamanhos: tabela(['Token', 'Valor', 'Uso'], [...linhasSimples('size', size), ...linhasSimples('layout', layout)]),
    opacidade: tabela(['Token', 'Valor', 'Uso'], linhasSimples('opacity', opacity)),
    sombras: tabela(['Token', 'Valor (`boxShadow`)', 'Uso'], linhasSimples('shadow', shadow)),
    degrades: tabela(
      ['Token', 'Receita (camadas de cima para baixo)', 'Uso'],
      Object.entries(gradients).map(([nome, receita]) => [
        cod(`gradients.${nome}`),
        receita.split(/,\s*(?=(?:radial|linear)-gradient\()/).map((camada) => cod(camada)).join('<br>'),
        descricaoDoToken(`gradients.${nome}`) ?? '',
      ]),
    ),
    movimento: tabela(['Token', 'Valor', 'Uso'], linhasSimples('motion', motion)),

    'icones-categorias': tabela(
      ['Ícone do lembrete', 'Lucide', 'Giro na lista'],
      Object.entries(ICON_NAME).map(([chave, nome]) => [cod(chave), cod(nome), GIRO_NA_LISTA[chave as IconKey] !== undefined ? `${GIRO_NA_LISTA[chave as IconKey]}°` : '—']),
    ),
    'icones-interface': tabela(
      ['Uso', 'Lucide'],
      [...Object.entries(TAB_ICON).map(([aba, nome]) => [`Aba ${aba}`, cod(nome)]), ...Object.entries(UI_ICON).map(([uso, nome]) => [uso, cod(nome)])],
    ),
  };
}

/** Reescreve só o que está entre os marcadores; o resto do texto fica intacto. */
export function aplicarBlocos(texto: string, blocos: Record<string, string>): string {
  return Object.entries(blocos).reduce((t, [id, conteudo]) => {
    const marcador = new RegExp(`(<!-- tokens:${id}:inicio -->)[\\s\\S]*?(<!-- tokens:${id}:fim -->)`);
    return t.replace(marcador, (_tudo, ini: string, fim: string) => `${ini}\n${conteudo}\n${fim}`);
  }, texto);
}

/** Tokens citados entre crases no texto ("`colors.text.primary`"). Aceita também o nome de um grupo ("`colors.category`"). */
export function tokensCitadosNoTexto(texto: string): string[] {
  const raizes = Object.keys(GRUPOS).concat('textStyles').join('|');
  const achados = [...texto.matchAll(new RegExp(`\`((?:${raizes})(?:\\.[A-Za-z0-9]+)+)\``, 'g'))].map((m) => m[1]);
  return [...new Set(achados)];
}
